### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by Benmuiruri** [Benmuiruri/rails-cook-book#17]
In this first milestone, our group was able to: 

- Successfully create and copy our Kanban cards 
- Create issues for group tasks and each group member Assign tasks to the group and group members 

Our group consists of 2 members and we are: 

1. @EzekielUtshudi - Team Member # 1 
2. @Benmuiruri  Team Member # 2  

The Link to our project is [Rails Cook Book](https://github.com/users/Benmuiruri/projects/4)

Thank you for taking the time to review this Issue 🙏

**Comment by dasileker** [comment]
### **Hi @Benmuiruri,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
